Complete lesson4
PavelTkachenko/reblog pull request #5
Opened 2017-06-04 10:11 UTC by PavelTkachenko

2017-06-06 10:46 UTC, index01d requested changes
Привет, извиняюсь за долгую проверку, но:

1) Нужно устранить ошибки из отчета ESLint (видим 6 проблем в src)
2) react-hot-loader и горячая перезагрузка очевидно отрабатывают некорректно. Проверить очень просто: когда стираешь элемент с картинкой, то слетает количество лайков. Предположительно это потому что плагина хот лоадера нет в конфиге babel'a
3) В консоли есть ошибки валидации PropType'ов

2017-06-10 05:48 UTC, index01d approved these changes

2017-06-10 05:48 UTC, index01d commented on src/components/ui/MetaBlock.jsx
> +const MetaBlock = ({ author }) => (
хей, а куда они делись?

2017-06-10 05:53 UTC, PavelTkachenko commented on src/components/ui/MetaBlock.jsx
> +const MetaBlock = ({ author }) => (
Не вписывались в design =) Но я их верну в следующем пулл-реквесте. Уже придумал как будет выглядеть.

2017-06-10 05:53 UTC, PavelTkachenko commented on src/components/ui/MetaBlock.jsx
> +const MetaBlock = ({ author }) => (
Спасибо за проверку. Блин, курс очень крутой. Мне нравится, пошел роутер учить.

2017-06-21 05:02 UTC, merged