Complete lesson5
PavelTkachenko/reblog pull request #6
Opened 2017-06-21 05:03 UTC by PavelTkachenko

2017-06-21 14:17 UTC, index01d requested changes

2017-06-21 14:17 UTC, index01d commented on src/components/containers/MoviePage.jsx
> +      <Grid fluid>
презентационная логика оказалась в контейнере, должна быть в представлении (View). Все, что должен сделать контейнер – это получить данные, подготовить коллбэки и отдать их презентационному компоненту

2017-06-21 14:17 UTC, index01d commented on src/components/containers/MoviePage.jsx
> +import { API_PATH } from '../../constants/conf';
при импорте везде нужно использовать абсолютные пути (constants/conf), а не относительные

2017-06-21 14:17 UTC, index01d commented on src/components/containers/MoviePage.jsx
> +  static renderLoading() {
Раз уж этот метод везде одинаковый, то можно оформить его в виде HOC-компонента
```
export (Component) => (props) => (
  props.isLoading ? 
    props.loadingComponent ? React.createElement(props.loadingComponent) : <Loading /> 
    : <Component {{...omit(props, ['isLoading', 'loadingComponent'])}} />
);
```

и затем применить его ко всем компонентам, например вместо `export default MoviePage` написать `export default withLoading(MoviePage)`

2017-06-21 14:17 UTC, index01d commented on src/App.jsx
> +    <MainLayout>
а что, если часть роутов будет не в MainLayout? :)

2017-06-21 14:18 UTC, index01d commented on src/components/containers/MoviePage.jsx
> +  static renderLoading() {
здесь loadingComponent, это специальное свойство на случае, если нужно будет задать отдельный компонент с информацией о загрузке для данного конкретного кейса. Свойство isLoading должно приходить в представление (обернутое в HOC) от контейнера

2017-06-25 07:47 UTC, index01d requested changes
по сути контейнеры почему-то заименованы в fetchers, что уж совсем нестандартно и плохо читаемо опытными разработчиками

2017-06-25 07:47 UTC, index01d commented on package.json
> +    "recompose": "^0.23.5",
появилась неиспользуемая зависимость

2017-06-25 07:47 UTC, index01d commented on src/components/fetchers/WithReviewData.jsx
> +      ? <Loading />
Хорошо, что Loading выехал в отдельный модуль, но все еще остается уродливая повторяющаяся проверка. По идее я имел ввиду что контейнер должен остаться обычным компонентом (не HOC), что впрочем непринципиально. HOC одним из плюсов должен приводить к отсутствию дублирования кода, а эта проверка тащится из контейнера в контейнер. Так вот идея была в том, чтобы сделать HOC-компонент withLoading, который бы обрабатывал свойство isLoading и осуществлял эту условную проверку. Тогда была бы только одна точка в приложении с таким условием.

2017-06-25 07:47 UTC, index01d commented on src/components/fetchers/WithReviewData.jsx
> +const WithReviewData = (BaseComponent) =>
Название на With в данном случае плохо считывается и With выглядит избыточным. постфиксное именование с Container было бы во всяком случае более знакомо большинству разработчиков.

2017-06-25 07:50 UTC, index01d commented on src/components/fetchers/WithReviewData.jsx
> +      ? <Loading />
тогда в контейнере останется просто рендеринг результата выполнения `withLoading(BaseComponent)` без лишнего низкоуровневого кода проверок

2017-06-25 15:55 UTC, PavelTkachenko commented on src/App.jsx
> +    <MainLayout>
Вот тут остается вопрос. Когда я MainLayout выношу внутрь Switch, то внизу всегда рендерится последний Route NotFound.

2017-06-26 08:14 UTC, index01d approved these changes
В общем изменений таких каких хотел, пока не нашел. Но видел на форуме, что понимание пришло, так что ставлю прув, чтобы можно было двигаться дальше. Но ближе к 8му уроку буду упираться, чтобы переделывали в состояние "хорошо" :)

2017-07-21 14:22 UTC, merged